[package]
name = "manual_routes"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
rocket = { path = "../../core/lib" }
tokio = { version = "0.2.0", features = ["io-util"] }
