[package]
name = "content_types"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
tokio = { version = "0.2.0", features = ["io-util"] }
rocket = { path = "../../core/lib" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
